<?php
$eZTranslationCacheCodeDate = 1058863428;

$CacheInfo = array (
  'charset' => 'utf-8',
);
$TranslationInfo = array (
  'context' => 'design/admin2/ajaxuploader',
);

$TranslationRoot = array (
  '940f95c268f09b656ce2c05e0e80d4cf' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Go to the parent level',
    'comment' => NULL,
    'translation' => 'Go to the parent level',
    'key' => '940f95c268f09b656ce2c05e0e80d4cf',
  ),
  '49a4e91cd286500482b39b64d24660d6' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Step 1/3: Upload a file',
    'comment' => NULL,
    'translation' => 'Step 1/3: Upload a file',
    'key' => '49a4e91cd286500482b39b64d24660d6',
  ),
  'e023a266fd858cbb540365a016c57b36' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Name',
    'comment' => NULL,
    'translation' => 'Name',
    'key' => 'e023a266fd858cbb540365a016c57b36',
  ),
  'ec6a3136e38cbbc52e66083e3c345c75' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Type',
    'comment' => NULL,
    'translation' => 'Type',
    'key' => 'ec6a3136e38cbbc52e66083e3c345c75',
  ),
  'f76eccbb8e4c39193805b86647559b0e' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Section',
    'comment' => NULL,
    'translation' => 'Section',
    'key' => 'f76eccbb8e4c39193805b86647559b0e',
  ),
  'f6656a3d5634d2c5db968b9f6e2af718' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'prev',
    'comment' => NULL,
    'translation' => 'prev',
    'key' => 'f6656a3d5634d2c5db968b9f6e2af718',
  ),
  'a391e78c8c05369db4201c83435dc81c' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'next',
    'comment' => NULL,
    'translation' => 'next',
    'key' => 'a391e78c8c05369db4201c83435dc81c',
  ),
  '77b0ddd29421dfb0ad286a170347e65e' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Step 2/3: Choose a location for the new \'%class\' object',
    'comment' => NULL,
    'translation' => 'Step 2/3: Choose a location for the new \'%class\' object',
    'key' => '77b0ddd29421dfb0ad286a170347e65e',
  ),
  '2714572ea784fac44f41a587a15bd410' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Please choose a location for the \'%class\' object that is going to be created from it.',
    'comment' => NULL,
    'translation' => 'Please choose a location for the \'%class\' object that is going to be created from it.',
    'key' => '2714572ea784fac44f41a587a15bd410',
  ),
  'ac442d7e480c1496b4b83a06c149ffa7' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Choose this location',
    'comment' => NULL,
    'translation' => 'Choose this location',
    'key' => 'ac442d7e480c1496b4b83a06c149ffa7',
  ),
  '921dc1c7b4d5c8c120e86199913a50ef' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Close',
    'comment' => NULL,
    'translation' => 'Close',
    'key' => '921dc1c7b4d5c8c120e86199913a50ef',
  ),
  'f2692d59aa757499c9911c065d09b213' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Step 3/3: Preview of \'%name\' (%class)',
    'comment' => NULL,
    'translation' => 'Step 3/3: Preview of \'%name\' (%class)',
    'key' => 'f2692d59aa757499c9911c065d09b213',
  ),
  '1d84ba9391b700f67a38980f263b7cf6' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Add',
    'comment' => NULL,
    'translation' => 'Add',
    'key' => '1d84ba9391b700f67a38980f263b7cf6',
  ),
  '989d0a235a4e4b2650af38ec29784beb' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'File',
    'comment' => NULL,
    'translation' => 'File',
    'key' => '989d0a235a4e4b2650af38ec29784beb',
  ),
  'c0ee248d690b2d04eef63c62af0fd95a' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Required',
    'comment' => NULL,
    'translation' => 'Required',
    'key' => 'c0ee248d690b2d04eef63c62af0fd95a',
  ),
  '2fda7501e55f891006fcace015755722' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'The name will be autogenerated',
    'comment' => NULL,
    'translation' => 'The name will be autogenerated',
    'key' => '2fda7501e55f891006fcace015755722',
  ),
  '36281097d30745355df8ddf9ad2683f7' => 
  array (
    'context' => 'design/admin2/ajaxuploader',
    'source' => 'Upload the file',
    'comment' => NULL,
    'translation' => 'Upload the file',
    'key' => '36281097d30745355df8ddf9ad2683f7',
  ),
);
?>
